[[redirects]]
  from = "/"
  to = "http://54.205.200.84:5000/analyze"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"